name: servidor_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  postgres: ^2.6.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
